### ISSUE TITLE
Todo app 요구사항 명세서 작성

### ISSUE THREAD

**Issue by choi-eun-hwa** [choi-eun-hwa/todo-app#1]
###만들고자 하는 기능이 무엇인가요?
Todo 생성기능
Todo 수정기능
Todo 삭제기능
Todo 이동기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] 각 기능들을 연결하는 버튼이 있어야한다.
2. [x] 어떤 UX가 필요한지 생각해봐야한다.
3. [x] 적절한 UI를 위해 래퍼런스를 찾아보고 참고한다.
4. [ ] 컴포넌트를 나누어 피그마 툴을 이용하여 작성해보아야한다.

### 예상 작업 시간
4h
